services:
  # Verdaccio NPM Registry
  verdaccio:
    build:
      context: .
      dockerfile: Dockerfile.verdaccio
    ports:
      - "4873:4873"
    volumes:
      - verdaccio_storage:/verdaccio/storage
      - verdaccio_conf:/verdaccio/conf
      - ./config:/verdaccio/conf:ro
      - ./plugins:/verdaccio/plugins:ro
    environment:
      - VERDACCIO_PROTOCOL=http
      - VERDACCIO_PORT=4873
      - NODE_ENV=development
      - APPROVAL_API_URL=http://approval-api:3003
    depends_on:
      - dynamodb-local
      - approval-api
    networks:
      - verdaccio-net

  # Mock AWS Services using LocalStack
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4572:4572"
    environment:
      - SERVICES=s3,dynamodb,sns,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CLEAR_TMP_FOLDER=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/tmp/localstack
    networks:
      - verdaccio-net

  # DynamoDB Local for approval tracking
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - verdaccio-net

  # Approval API Service (simulates Lambda function)
  approval-api:
    build:
      context: .
      dockerfile: Dockerfile.approval-api
    ports:
      - "3003:3001"
    environment:
      - NODE_ENV=development
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_ENDPOINT=http://localstack:4566
      - SNS_ENDPOINT=http://localstack:4566
      - APPROVAL_TABLE=package-approvals
    depends_on:
      - dynamodb-local
      - localstack
    networks:
      - verdaccio-net

  # Approval Dashboard
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3003
      - REACT_APP_VERDACCIO_URL=http://localhost:4873
    depends_on:
      - approval-api
    networks:
      - verdaccio-net

  # Initialize AWS resources in LocalStack
  aws-setup:
    image: amazon/aws-cli:latest
    depends_on:
      - localstack
      - dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./scripts:/scripts
    command: >
      sh -c "
        sleep 10 &&
        aws --endpoint-url=http://localstack:4566 dynamodb create-table \
          --table-name package-approvals \
          --attribute-definitions \
            AttributeName=packageName,AttributeType=S \
            AttributeName=version,AttributeType=S \
          --key-schema \
            AttributeName=packageName,KeyType=HASH \
            AttributeName=version,KeyType=RANGE \
          --billing-mode PAY_PER_REQUEST &&
        aws --endpoint-url=http://localstack:4566 s3 mb s3://verdaccio-storage &&
        aws --endpoint-url=http://localstack:4566 sns create-topic --name package-approvals &&
        echo 'AWS resources initialized'
      "
    networks:
      - verdaccio-net

volumes:
  verdaccio_storage:
  verdaccio_conf:
  localstack_data:

networks:
  verdaccio-net:
    driver: bridge

