services:
  # Upstream Verdaccio instance - acts as a proxy to npmjs and hosts test packages
  verdaccio-upstream:
    image: verdaccio/verdaccio:6
    container_name: verdaccio-upstream
    ports:
      - "4872:4873"
    volumes:
      - ./docker-data/upstream/storage:/verdaccio/storage
      - ./docker-data/upstream/conf:/verdaccio/conf
      - ./upstream-config.yaml:/verdaccio/conf/config.yaml
    environment:
      - VERDACCIO_USER_NAME=admin
      - VERDACCIO_USER_PWD=admin123
    networks:
      - verdaccio-network

  # Downstream Verdaccio instance with HMR - uses quarantine plugin
  verdaccio-downstream:
    build:
      context: ./downstream
      additional_contexts:
        libs: ./dist/libs
      dockerfile: Dockerfile.downstream.verdaccio
    container_name: verdaccio-downstream
    ports:
      - "4873:4873"
    volumes:
      - ./docker-data/downstream/storage:/verdaccio/storage
      - ./docker-data/downstream/conf:/verdaccio/conf
      - ./downstream-config.yaml:/verdaccio/conf/config.yaml
      # Mount the source code directly for HMR
      - ./dist/libs/:/app/plugins:ro
      - ./docker-data/downstream/quarantine:/verdaccio/quarantine
      # Mount nodemon config
      - ./nodemon.json:/app/nodemon.json
    environment:
      - VERDACCIO_USER_NAME=admin
      - VERDACCIO_USER_PWD=admin123
      - NODE_ENV=development
    depends_on:
      - verdaccio-upstream
    networks:
      - verdaccio-network
    # Override the default command to use nodemon
    command: ["npm", "run", "dev"]

  # Test package publisher - publishes suspicious packages to upstream
  test-publisher:
    image: node:18-alpine
    container_name: test-publisher
    working_dir: /app
    volumes:
      - ./test-packages:/app/test-packages
      - ./scripts:/app/scripts
    networks:
      - verdaccio-network
    depends_on:
      - verdaccio-upstream
    command: sh -c "apk add curl && sleep infinity"

networks:
  verdaccio-network:
    driver: bridge

volumes:
  upstream-storage:
  downstream-storage:
