* Typescript config

The Typescript config in the root of the project is configured to compile to modern ESM syntax
The Typescript config in the libs/verdaccio-approval-plugin folder is configured to compile to CommonJS syntax as required by verdaccio.
This is a good example of how nx creates a "Standard operating procedure" which can be overridden by individual projects as needs be.

* Debt

** Test Packages publishing script

scripts/publish-test-packages.sh

This does not work. Instead as a workaround the test-publisher container has been jerry rigged as follows

#+begin_src yaml
  test-publisher:
    image: node:18-alpine
    container_name: test-publisher
    working_dir: /app
    volumes:
      - ./test-packages:/app/test-packages
      - ./scripts:/app/scripts
    networks:
      - verdaccio-network
    depends_on:
      - verdaccio-upstream
    command: sh -c "apk add curl && sleep infinity"
#+end_src

If you launch the docker stack as follows

#+begin_src sh
  docker-compose up --build --force-recreate
  # Then shell into the test-publisher container
  docker exec -it test-publisher /bin/ash
  # Then change directory to the test package you wish to publish, for example
  cd test-packages/backdoor-util-test-package/
  # Then login manually
  # username: admin
  # password: admin123
  npm login --registry http://verdaccio-upstream:4873
  # Then publish manually
  npm publish --registry http://verdaccio-upstream:4873  
#+end_src

** Plugin installation in Docker container

This has been cludged with the entrypoint.sh such that

#+begin_src sh 
  # Check if we're in development mode (plugin directory is mounted)
if [ "$NODE_ENV" = "development" ] && [ -d "/verdaccio/plugins/verdaccio-approval-plugin" ]; then
    echo "Development mode detected - installing plugin dependencies"
    cd /verdaccio/plugins/verdaccio-approval-plugin
    npm install
	ln -sf /verdaccio/plugins/verdaccio-approval-plugin /app/node_modules/verdaccio-approval-plugin

	cd /verdaccio/plugins/verdaccio-quarantine-plugin
	npm install
	ln -sf /verdaccio/plugins/verdaccio-quarantine-plugin /app/node_modules/verdaccio-quarantine-plugin
	
    echo "Plugin setup complete. Starting verdaccio in development mode with nodemon"
    cd /app
    exec npm run dev
else
    echo "Production mode - starting verdaccio directly"
    exec verdaccio
fi
#+end_src

we have to cd into each plugin folder and run npm i and then create a symbolic link from the plugin folder to the corresponding /app/node_modules folder for verdaccio to be able to recognise the plugin.
This does not scale very well, but the likelihood of writing copious plugins is low so this may not be worth solving other than for my own personal satisfaction.

** Error handling

Need to find a better way to handle the unknown error type in catch blocks

#+begin_src typescript
  // https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript
  catch (err) {
        config.log(`Retry ${i} failed: ${JSON.stringify(err, 2, null)}`);
        error = err;
      }
#+end_src
